
// This file conatin the data in the json format with details of the products

export const product = [

  {
    "id": 1,
    "title": "Men's casual sneakers",
    "description": "comfortable",
    "category": "Male's footwear bottomwear",
    "image": " https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg?auto=compress&cs=tinysrgb&w=600",
    "price": 590,
    "brand": "streetwalk",
    "size": ["8", "9", "10"],
    "colors": ["Gray", "Black"],
    "stock": 120,
    "rating": { "rate": 4.6, "count": 200 },
    "material": "canvas",
    "subcategory": "bottomwear",
    "careInstructions": "Wipe with a damp cloth.",
    "Categorie": "M",
    "wear": "B",
  },
  {
    "id": 2,
    "title": "Women's summer dress",
    "description": "lightweight and breezy",
    "category": "women's clothing",
    "image": "https://images.pexels.com/photos/29129854/pexels-photo-29129854/free-photo-of-stylish-woman-sitting-outdoors-in-sunset-light.jpeg?auto=compress&cs=tinysrgb&w=600",
    "price": 890,
    "brand": "fashionista",
    "subcategory": "topwear",
    "size": ["S", "M", "L"],
    "colors": ["Floral", "Solid Red"],
    "stock": 75,
    "rating": { "rate": 4.7, "count": 120 },
    "material": "cotton",
    "wear": "T",
    "careInstructions": "Machine wash cold."
  },
  {
    "id": 3,
    "title": "Children's graphic t-shirt",
    "description": "fun designs for kids",
    "category": "children's clothing",
    "image": "https://images.pexels.com/photos/15179152/pexels-photo-15179152/free-photo-of-studio-shot-of-a-little-boy-wearing-a-t-shirt-with-a-picture-of-a-dinosaur.jpeg?auto=compress&cs=tinysrgb&w=600",
    "price": 250,
    "subcategory": "topwear",
    "brand": "kidstyle",
    "size": ["4", "6", "8"],
    "colors": ["Blue", "Green", "Pink"],
    "stock": 200,
    "rating": { "rate": 4.5, "count": 150 },
    "material": "cotton",
    "Categorie": "C",
    "wear": "T",
    "careInstructions": "Machine wash with like colors."
  },
  {
    "id": 4,
    "title": "Men's hoodie",
    "description": "cozy and stylish",
    "category": "male's clothing",
    "image": "https://images.pexels.com/photos/15389454/pexels-photo-15389454/free-photo-of-men-and-women-in-hoodies.jpeg?auto=compress&cs=tinysrgb&w=600",
    "price": 1190,
    "subcategory": "topwear",
    "brand": "hoodieland",
    "size": ["M", "L", "XL"],
    "colors": ["Black", "Gray", "Navy"],
    "stock": 100,
    "wear": "T",
    "Categorie": "M",
    "rating": { "rate": 4.6, "count": 180 },
    "material": "fleece",
    "careInstructions": "Machine wash cold."
  },
  {
    "id": 5,
    "title": "Men's wool coat",
    "description": "classic and versatile",
    "category": "male's clothing",
    "image": "https://images.pexels.com/photos/29037368/pexels-photo-29037368/free-photo-of-stylish-man-in-blue-coat-against-orange-brick-wall.jpeg?auto=compress&cs=tinysrgb&w=600",
    "price": 1290,
    "brand": "denimco",
    "size": ["S", "M", "L"],
    "colors": ["Light Wash", "Dark Wash"],
    "stock": 60,
    "wear": "T",
    "subcategory": "topwear",
    "Categorie": "M",
    "rating": { "rate": 4.8, "count": 200 },
    "material": "denim",
    "careInstructions": "Machine wash separately."
  },
  {
    "id": 6,
    "title": "Sneaker",
    "description": "warm and stylish",
    "category": "male's clothing",
    "image": "https://images.pexels.com/photos/19090/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "price": 1490,
    "brand": "littleadventurer",
    "size": ["4", "6", "8", "10"],
    "colors": ["Red", "Blue"],
    "stock": 80,
    "wear": "B",
    "Categorie": "M",
    "subcategory": "bottomwear",
    "rating": { "rate": 4.7, "count": 90 },
    "material": "polyester",
    "careInstructions": "Wipe clean; do not machine wash."
  },
  {

    "id": 7,
    "title": "Men's chinos",
    "description": "smart and comfortable",
    "category": "male's clothing",
    "image": "https://images.pexels.com/photos/10074957/pexels-photo-10074957.jpeg?auto=compress&cs=tinysrgb&w=600",
    "price": 990,
    "Categorie": "M",
    "wear": "B",
    "brand": "smartwear",
    "size": ["32", "34", "36"],
    "colors": ["Beige", "Navy"],
    "stock": 100,
    "subcategory": "bottomwear",
    "rating": { "rate": 4.5, "count": 140 },
    "material": "cotton",
    "careInstructions": "Machine wash cold."
  },
  {
    "id": 8,
    "title": "Women's yoga pants",
    "description": "perfect for workouts",
    "category": "women's clothing",
    "image": "https://images.pexels.com/photos/4151061/pexels-photo-4151061.jpeg?auto=compress&cs=tinysrgb&w=600",
    "price": 750,
    "brand": "activewear",
    "size": ["S", "M", "L"],
    "colors": ["Black", "Gray", "Purple"],
    "stock": 120,
    "subcategory": "bottomwear",
    "Categorie": "W",
    "wear": "B",
    "rating": { "rate": 4.9, "count": 200 },
    "material": "spandex blend",
    "careInstructions": "Machine wash cold."
  },
  {
    "id": 9,
    "title": "Women's shoe",
    "description": "elegant and professional",
    "category": "men's clothing",
    "image": "https://images.pexels.com/photos/1335463/pexels-photo-1335463.jpeg?auto=compress&cs=tinysrgb&w=600",
    "price": 1090,
    "Categorie": "W",
    "wear": "B",
    "subcategory": "bottomwear",
    "brand": "playtime",
    "size": ["4", "6", "8"],
    "colors": ["Yellow", "Blue", "Red"],
    "stock": 150,
    "rating": { "rate": 4.6, "count": 100 },
    "material": "cotton",
    "careInstructions": "Machine wash with like colors."
  },
  {
    "id": 10,
    "title": "Men's polo shirt",
    "description": "classic fit and breathable",
    "category": "male's clothing",
    "image": "https://images.pexels.com/photos/5950127/pexels-photo-5950127.jpeg?auto=compress&cs=tinysrgb&w=600",
    "price": 650,
    "wear": "T",
    "subcategory": "topwear",
    "brand": "polostyle",
    "size": ["M", "L", "XL"],
    "colors": ["White", "Black", "Navy"],
    "stock": 150,
    "Categorie": "M",
    "rating": { "rate": 4.6, "count": 130 },
    "material": "cotton blend",
    "careInstructions": "Machine wash cold."
  },
  {
    "id": 11,
    "title": "Women's shoes",
    "description": "elegant and professional",
    "category": "women's clothing",
    "image": " https://images.pexels.com/photos/134064/pexels-photo-134064.jpeg?auto=compress&cs=tinysrgb&w=300",
    "price": 1090,
    "subcategory": "bottomwear",
    "wear": "B",
    "brand": "officewear",
    "size": ["S", "M", "L"],
    "colors": ["Black", "Charcoal", "Beige"],
    "stock": 80,
    "Categorie": "W",
    "rating": { "rate": 4.7, "count": 110 },
    "material": "polyester",
    "careInstructions": "Dry clean only."
  },
  {
    "id": 12,
    "title": "Children's raincoat",
    "description": "bright and waterproof",
    "category": "children's clothing",
    "image": "https://images.pexels.com/photos/14753788/pexels-photo-14753788.jpeg?auto=compress&cs=tinysrgb&w=600",
    "price": 950,
    "subcategory": "topwear",
    "wear": "T",
    "brand": "rainyday",
    "size": ["4", "6", "8"],
    "colors": ["Yellow", "Pink", "Blue"],
    "stock": 70,
    "Categorie": "C",
    "rating": { "rate": 4.8, "count": 85 },
    "material": "PVC",
    "careInstructions": "Wipe clean; do not machine wash."
  },
  {
    "id": 13,
    "title": "Men's dress shirt",
    "description": "perfect for formal occasions",
    "category": "male's clothing",
    "image": " https://images.pexels.com/photos/27333760/pexels-photo-27333760/free-photo-of-portrait-of-a-man-smiling.jpeg?auto=compress&cs=tinysrgb&w=600",
    "price": 990,
    "subcategory": "summerwear",
    "wear": "T",
    "Categorie": "M",
    "brand": "formalguy",
    "size": ["S", "M", "L", "XL", "XX", "XXL"],
    "colors": ["White", "Light Blue", "Gray"],
    "stock": 100,
    "rating": { "rate": 4.5, "count": 160 },
    "material": "cotton",
    "careInstructions": "Machine wash cold and iron."
  },
  {
    "id": 14,
    "title": "women's tank top",
    "description": "comfortable and stylish",
    "category": "women's clothing",
    "image": "https://images.pexels.com/photos/6988570/pexels-photo-6988570.jpeg?auto=compress&cs=tinysrgb&w=600 ",
    "price": 400,
    "subcategory": "topwear",
    "wear": "T",
    "brand": "casualwear",
    "size": ["S", "M", "L"],
    "colors": ["Black", "White", "Pink"],
    "stock": 120,
    "Categorie": "W",
    "rating": { "rate": 4.4, "count": 150 },
    "material": "cotton",
    "careInstructions": "Machine wash with like colors."
  },
  {
    "id": 15,
    "title": "children's overall shorts",
    "description": "fun and playful",
    "category": "children's clothing",
    "image": "https://images.pexels.com/photos/4715315/pexels-photo-4715315.jpeg?auto=compress&cs=tinysrgb&w=600",
    "price": 600,
    "wear": "B",
    "brand": "playfulkids",
    "subcategory": "bottomwear",
    "size": ["4", "6", "8"],
    "colors": ["Denim", "Pink", "Green"],
    "stock": 90,
    "Categorie": "C",
    "rating": { "rate": 4.6, "count": 110 },
    "material": "cotton",
    "careInstructions": "Machine wash cold."
  },
  {
    "id": 16,
    "title": "men's bomber jacket",
    "description": "stylish and warm",
    "category": "male's clothing",
    "image": "https://images.pexels.com/photos/7129168/pexels-photo-7129168.jpeg?auto=compress&cs=tinysrgb&w=300",
    "wear": "T",
    "price": 1490,
    "Categorie": "M",
    "subcategory": "winterwear",
    "brand": "urbanwear",
    "size": ["M", "L", "XL"],
    "colors": ["Black", "Olive"],
    "stock": 50,
    "rating": { "rate": 4.7, "count": 130 },
    "material": "nylon",
    "careInstructions": "Dry clean only."
  },
  {
    "id": 17,
    "title": "women's maxi skirt",
    "description": "flowy and elegant",
    "category": "women's clothing",
    "image": "https://images.pexels.com/photos/11288126/pexels-photo-11288126.jpeg?auto=compress&cs=tinysrgb&w=300",
    "price": 950,
    "subcategory": "topwear",
    "wear": "B",
    "Categorie": "W",
    "brand": "bohostyle",
    "size": ["S", "M", "L"],
    "colors": ["Black", "Floral", "Red"],
    "stock": 65,
    "rating": { "rate": 4.8, "count": 90 },
    "material": "chiffon",
    "careInstructions": "Hand wash cold."
  },
  {
    "id": 18,
    "title": "children's pajamas",
    "description": "cozy for sleep",
    "category": "children's clothing",
    "image": "https://images.pexels.com/photos/29856955/pexels-photo-29856955/free-photo-of-children-in-pajamas-admiring-christmas-tree.jpeg?auto=compress&cs=tinysrgb&w=300",
    "price": 450,
    "wear": "B",
    "subcategory": "bottomwear",
    "Categorie": "C",
    "brand": "snugglers",
    "size": ["4", "6", "8"],
    "colors": ["Blue", "Pink"],
    "stock": 150,
    "rating": { "rate": 4.6, "count": 100 },
    "material": "cotton",
    "careInstructions": "Machine wash with like colors."
  },
  {
    "id": 19,
    "title": "men's cargo shorts",
    "description": "functional and stylish",
    "category": "male's clothing",
    "image": "https://images.pexels.com/photos/30989303/pexels-photo-30989303/free-photo-of-man-walking-at-night-in-urban-setting.jpeg?auto=compress&cs=tinysrgb&w=300",

    "price": 750,
    "wear": "B",
    "brand": "adventurewear",
    "size": ["32", "34", "36"],
    "subcategory": "bottomwear",
    "colors": ["Khaki", "Navy"],
    "stock": 110,
    "Categorie": "M",
    "rating": { "rate": 4.5, "count": 120 },
    "material": "cotton",
    "careInstructions": "Machine wash cold."
  },
  {
    "id": 20,
    "title": "women's knit sweater",
    "description": "soft and warm",
    "category": "women's clothing",
    "image": "https://images.pexels.com/photos/20344852/pexels-photo-20344852/free-photo-of-woman-in-sweater.jpeg?auto=compress&cs=tinysrgb&w=300",

    "price": 1190,
    "brand": "cozyknits",
    "size": ["S", "M", "L"],
    "colors": ["Cream", "Gray", "Dusty Pink"],
    "stock": 75,
    "wear": "T",
    "subcategory": "topwear",
    "Categorie": "W",
    "rating": { "rate": 4.6, "count": 140 },
    "material": "acrylic blend",
    "careInstructions": "Hand wash cold."
  },
  {
    "id": 21,
    "title": "children's printed leggings",
    "description": "colorful and stretchy",
    "category": "children's clothing",
    "image": "https://images.pexels.com/photos/10598819/pexels-photo-10598819.jpeg?auto=compress&cs=tinysrgb&w=300",
    "price": 400,
    "brand": "activekids",
    "size": ["4", "6", "8"],
    "colors": ["Rainbow", "Animal Print"],
    "stock": 130,
    "subcategory": "bottomwear",
    "wear": "B",
    "Categorie": "C",
    "rating": { "rate": 4.7, "count": 110 },
    "material": "spandex blend",
    "careInstructions": "Machine wash with like colors."
  },
  {
    "id": 22,
    "title": "men's casual blazer",
    "description": "smart and versatile",
    "category": "male's clothing",
    "image": "https://images.pexels.com/photos/30947674/pexels-photo-30947674/free-photo-of-stylish-man-posing-in-fashion-store-interior.jpeg?auto=compress&cs=tinysrgb&w=300",
    "price": 1590,
    "brand": "elegance",
    "size": ["M", "L", "XL"],
    "colors": ["Navy", "Charcoal"],
    "stock": 40,
    "subcategory": "winterwear",
    "wear": "T",
    "Categorie": "M",
    "rating": { "rate": 4.8, "count": 95 },
    "material": "polyester blend",
    "careInstructions": "Dry clean only."
  },
  {
    "id": 23,
    "title": "women's workout tank",
    "description": "breathable and lightweight",
    "category": "women's clothing",
    "image": "https://images.pexels.com/photos/5038829/pexels-photo-5038829.jpeg?auto=compress&cs=tinysrgb&w=300",
    "price": 550,
    "Categorie": "W",
    "brand": "fitgear",
    "size": ["S", "M", "L"],
    "subcategory": "topwear",
    "colors": ["Black", "Turquoise"],
    "stock": 100,
    "wear": "T",
    "rating": { "rate": 4.5, "count": 200 },
    "material": "moisture-wicking fabric",
    "careInstructions": "Machine wash cold."
  },
  {
    "id": 24,
    "title": "children's hooded sweatshirt",
    "description": "comfy and warm",
    "category": "children's clothing",
    "image": "https://images.pexels.com/photos/19640179/pexels-photo-19640179/free-photo-of-girl-in-a-sweatshirt-with-a-backpack.jpeg?auto=compress&cs=tinysrgb&w=300",
    "subcategory": "topwear",
    "price": 600,
    "Categorie": "C",
    "brand": "cozykids",
    "size": ["4", "6", "8"],
    "colors": ["Gray", "Red"],
    "stock": 90,
    "wear": "T",
    "rating": { "rate": 4.6, "count": 85 },
    "material": "fleece",
    "careInstructions": "Machine wash cold."
  },
  {
    "id": 25,
    "title": "men's swim trunks",
    "description": "quick-drying and stylish",
    "category": "male's clothing",
    "image": "https://images.pexels.com/photos/6012007/pexels-photo-6012007.jpeg?auto=compress&cs=tinysrgb&w=300",
    "subcategory": "topwear",
    "Categorie": "M",
    "price": 700,
    "brand": "beachlife",
    "size": ["M", "L", "XL"],
    "colors": ["Blue", "Black"],
    "stock": 120,
    "wear": "T",
    "rating": { "rate": 4.4, "count": 150 },
    "material": "polyester",
    "careInstructions": "Rinse after use."
  },
  {
    "id": 26,
    "title": "women's midi dress",
    "description": "elegant for any occasion",
    "category": "women's clothing",
    "image": "https://images.pexels.com/photos/6540009/pexels-photo-6540009.jpeg?auto=compress&cs=tinysrgb&w=300",
    "subcategory": "topwear",
    "price": 1290,
    "brand": "fashionista",
    "size": ["S", "M", "L"],
    "colors": ["Black", "Green Floral"],
    "stock": 70,
    "wear": "T",
    "Categorie": "W",
    "rating": { "rate": 4.9, "count": 110 },
    "material": "rayon",
    "careInstructions": "Machine wash cold."
  },
  {
    "id": 27,
    "title": "children's graphic hoodie",
    "description": "fun and warm",
    "category": "children's clothing",
    "image": "https://images.pexels.com/photos/10217697/pexels-photo-10217697.jpeg?auto=compress&cs=tinysrgb&w=300",
    "subcategory": "topwear",
    "price": 700,
    "brand": "coolkids",
    "size": ["4", "6", "8"],
    "colors": ["Black", "Navy"],
    "stock": 100,
    "wear": "T",
    "Categorie": "C",
    "rating": { "rate": 4.6, "count": 90 },
    "material": "cotton blend",
    "careInstructions": "Machine wash cold."
  }

]

